name: demis
channels:
  - PyTorch
  - anaconda
  - pytorch
  - photosynthesis-team
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - blas=1.0
  - boost-cpp=1.74.0
  - bzip2=1.0.8
  - ca-certificates=2022.12.7
  - cgal-cpp=5.5
  - colorama=0.4.6
  - cudatoolkit=10.2.89
  - eigen=3.4.0
  - ffmpeg=4.4.0
  - freetype=2.12.1
  - gmp=6.2.1
  - gnutls=3.6.13
  - gudhi=3.7.1
  - icu=68.2
  - jpeg=9b
  - lame=3.100
  - ld_impl_linux-64=2.36.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.4.2
  - libgcc-ng=12.1.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - liblapack=3.9.0
  - libnsl=2.0.0
  - libpng=1.6.38
  - libsqlite=3.39.4
  - libstdcxx-ng=12.1.0
  - libtiff=4.2.0
  - libuuid=2.32.1
  - libuv=1.44.2
  - libvpx=1.11.0
  - libwebp-base=1.2.4
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - mpfr=4.1.0
  - ncurses=6.3
  - nettle=3.6
  - ninja=1.11.0
  - numpy=1.23.1
  - numpy-base=1.23.1
  - olefile=0.46
  - openh264=2.1.1
  - openssl=3.0.8
  - pip=22.2.2
  - piq=0.7.0
  - python=3.8.13
  - python_abi=3.8
  - pytorch=1.8.1
  - readline=8.1.2
  - scikit-learn=1.2.0
  - setuptools=65.4.1
  - six=1.16.0
  - sqlite=3.39.4
  - tbb=2021.6.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - torchvision=0.9.1
  - typing_extensions=4.4.0
  - wheel=0.37.1
  - x264=1!161.3030
  - xz=5.2.6
  - zlib=1.2.12
  - zstd=1.4.9
  - pip:
    - absl-py==1.2.0
    - affine==2.4.0
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - albumentations==0.5.1
    - anyio==3.6.1
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - astroid==2.12.10
    - asttokens==2.0.8
    - async-timeout==4.0.2
    - attrs==22.1.0
    - autopep8==1.7.0
    - babel==2.10.3
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - cachetools==5.2.0
    - certifi==2022.9.24
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - click==8.0.4
    - click-plugins==1.1.1
    - cligj==0.7.2
    - contourpy==1.0.5
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.5.1
    - distlib==0.3.6
    - einops==0.3.0
    - entrypoints==0.4
    - executing==1.1.0
    - fastjsonschema==2.16.2
    - filelock==3.8.0
    - fonttools==4.37.4
    - frozenlist==1.3.1
    - fsspec==2022.8.2
    - future==0.18.2
    - google-auth==2.12.0
    - google-auth-oauthlib==0.4.6
    - graphslam==0.0.8
    - grpcio==1.43.0
    - h5py==3.1.0
    - idna==3.4
    - imageio==2.22.1
    - imgaug==0.4.0
    - importlib-metadata==5.0.0
    - importlib-resources==5.9.0
    - ipykernel==6.16.0
    - ipython==8.5.0
    - ipython-genutils==0.2.0
    - isort==5.10.1
    - jedi==0.18.1
    - jinja2==3.1.2
    - joblib==1.2.0
    - json5==0.9.10
    - jsonschema==4.16.0
    - jupyter-client==7.3.5
    - jupyter-core==4.11.1
    - jupyter-server==1.19.1
    - jupyterlab==3.4.8
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.15.2
    - kiwisolver==1.4.4
    - kornia==0.4.1
    - lazy-object-proxy==1.7.1
    - loguru==0.5.3
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.0
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - msgpack==1.0.4
    - multidict==6.0.2
    - nbclassic==0.4.5
    - nbclient==0.7.0
    - nbconvert==7.2.1
    - nbformat==5.6.1
    - nest-asyncio==1.5.6
    - networkx==2.8.7
    - notebook==6.4.12
    - notebook-shim==0.1.0
    - oauthlib==3.2.1
    - opencv-python==4.4.0.46
    - opencv-python-headless==4.6.0.66
    - packaging==21.3
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - phasepack==1.5
    - pickleshare==0.7.5
    - pillow==9.2.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.2
    - prometheus-client==0.14.1
    - prompt-toolkit==3.0.31
    - protobuf==3.19.6
    - psutil==5.9.2
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycodestyle==2.9.1
    - pycparser==2.21
    - pydeprecate==0.3.0
    - pyfftw==0.13.1
    - pygments==2.13.0
    - pylint==2.15.3
    - pyparsing==3.0.9
    - pyrsistent==0.18.1
    - python-dateutil==2.8.2
    - pytorch-lightning==1.3.5
    - pytz==2022.4
    - pywavelets==1.4.1
    - pyyaml==5.4.1
    - pyzmq==24.0.1
    - rasterio==1.3.5
    - ray==2.0.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - scikit-image==0.19.3
    - scipy==1.9.1
    - send2trash==1.8.0
    - shapely==1.8.4
    - sniffio==1.3.0
    - snuggs==1.4.7
    - soupsieve==2.3.2.post1
    - stack-data==0.5.1
    - tensorboard==2.10.1
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - terminado==0.16.0
    - tifffile==2022.8.12
    - tinycss2==1.1.1
    - tomli==2.0.1
    - tomlkit==0.11.5
    - torchmetrics==0.6.0
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.4.0
    - urllib3==1.26.12
    - virtualenv==20.16.5
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.1
    - werkzeug==2.2.2
    - wrapt==1.14.1
    - yacs==0.1.8
    - yarl==1.8.1
    - zipp==3.8.1
