DATASET:
  PATH: "../../../datasets/DEMIS/"
  TILE_OVERLAP: 0.25
STITCHER:
  OUTPUT_PATH: "../../../output/DEMIS/"
  RESOLUTION_RATIO: 0.5
  MATCHING_METHOD: "loftr"
  TRANSFORM_TYPE: "affine"
  COMPOSITING_METHOD: "overwrite"
  COLORED_OUTPUT: False
  NORMALISE_INTENSITY: True
