DATASET:
  PATH: "../../datasets/DEMIS/"
  TILE_OVERLAP: 0.3
STITCHER:
  RESOLUTION_RATIO: 0.5
  MATCHING_METHOD: "loftr"
  TRANSFORM_TYPE: "affine"
  CONSTRUCTION_METHOD: "slam"
  COMPOSITING_METHOD: "overwrite"
  COLORED_OUTPUT: False
  NORMALISE_INTENSITY: False
LOFTR:
  CHECKPOINT_PATH: "LoFTR/weights/outdoor_ds.ckpt"
EVAL:
  SPLIT_PATH: "../../datasets/DEMIS/splits/test_list.txt"
