DATASET:
  PATH: "../../../datasets/TESCAN/2x2/"
  TILE_OVERLAP: 0.3
STITCHER:
  OUTPUT_PATH: "../../../output/TESCAN/2x2/"
  RESOLUTION_RATIO: 0.5
  MATCHING_METHOD: "loftr"
  TRANSFORM_TYPE: "affine"
  CONSTRUCTION_METHOD: "slam"
  COMPOSITING_METHOD: "overwrite"
  COLORED_OUTPUT: False
  NORMALISE_INTENSITY: True
